### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rsrinivasu7** [vinyll/django-imagefit#16]
Internal Server Error: /imagefit/resize/320x240/media/banners/Paytm.JPG
Traceback (most recent call last):
  File "/home/narsing/.local/lib/python3.5/site-packages/PIL/ImageFile.py", line 466, in _save
    fh = fp.fileno()
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/narsing/Desktop/couponsrack/src/django-imagefit/imagefit/views.py", line 66, in resize
    image.save()
  File "/home/narsing/Desktop/couponsrack/src/django-imagefit/imagefit/models.py", line 85, in save
    self.pil.save(image_str, ext_to_format(self.cached_name))
  File "/home/narsing/.local/lib/python3.5/site-packages/PIL/Image.py", line 1698, in save
    save_handler(self, fp, filename)
  File "/home/narsing/.local/lib/python3.5/site-packages/PIL/JpegImagePlugin.py", line 725, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/home/narsing/.local/lib/python3.5/site-packages/PIL/ImageFile.py", line 481, in _save
    fp.write(d)
TypeError: string argument expected, got 'bytes'[14/Nov/2016 17:06:21] "GET /media/stores/1mg.jpg HTTP/1.1" 200 16329

**Comment by vinyll** [comment]
Seems to have been fixed since.
Please reopen if errors still occurs with v0.6+
