### ISSUE TITLE
Doesn't support S3 Image backend right?

### ISSUE THREAD

**Issue by manuganji** [vinyll/django-imagefit#28]
Hi, I'm trying to use your package with [django-s3direct](https://github.com/bradleyg/django-s3direct) and it is raising a file error.

>  Internal Server Error: /imagefit/resize/150x150,C/https://s3.amazonaws.com/wRCTXuPgbEOtbTzhRI8Ht.png
 Traceback (most recent call last):
   File "/home/manu/.virtualenvs/project/lib/python3.5/site-packages/django/core/handlers/exception.   py", line 35, in inner
     response = get_response(request)
   File "/home/manu/.virtualenvs/project/lib/python3.5/site-packages/django/core/handlers/base.py",    line 128, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/home/manu/.virtualenvs/project/lib/python3.5/site-packages/django/core/handlers/base.py",    line 126, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/home/manu/.virtualenvs/project/lib/python3.5/site-packages/imagefit/views.py", line 40, in   resize
     image = Image(path=os.path.join(prefix, url))
   File "/home/manu/.virtualenvs/project/lib/python3.5/site-packages/imagefit/models.py", line 21, in  __init__
     self.pil = PilImage.open(path)
   File "/home/manu/.virtualenvs/project/lib/python3.5/site-packages/PIL/Image.py", line 2548, in open
     fp = builtins.open(filename, "rb")
 FileNotFoundError: [Errno 2] No such file or directory: 'https://s3.amazonaws.com/                    wRCTXuPgbEOtbTzhRI8Ht.png'

**Comment by manuganji** [comment]
Hi @vinyll thanks for your reply. I purposely edited the file url to not reveal the link. Is this package tested to work remotely hosted images?

**Comment by vinyll** [comment]
It is supposed to work with full url images.
Therefore there’s nothing like a notion of backend for aws s3 here, just reading content from a remote url.

If that was not the case you’re facing bug that shouldn’t be specific to aws.
Could you test with some other remote image?
My laptop died a couple of days ago and it makes it tricky for me to test these things.
Thanks 👌
