### ISSUE TITLE
RuntimeError: Settings already configured.

### ISSUE THREAD

**Issue by luk156** [vinyll/django-imagefit#44]
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/imagefit/models.py", line 2, in <module>
    from imagefit.conf import ext_to_format, settings
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/imagefit/conf.py", line 6, in <module>
    settings.configure()
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 139, in configure
    raise RuntimeError("Settings already configured.")
RuntimeError: Settings already configured.
/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

**Comment by vinyll** [comment]
Fixed in #47.
Please upgrade to django-imagegit 0.8.0
