### ISSUE TITLE
TypeError: was_modified_since() takes from 0 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by luk156** [vinyll/django-imagefit#45]
[02/Aug/2023 08:19:34] "GET /imagefit/media_resize/600x600/products_images/0515-2.png HTTP/1.1" 500 95555
Internal Server Error: /imagefit/media_resize/600x600/products_images/0500-2.png
Traceback (most recent call last):
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/imagefit/views.py", line 45, in resize
    if not was_modified_since(request.META.get('HTTP_IF_MODIFIED_SINCE'),
TypeError: was_modified_since() takes from 0 to 2 positional arguments but 3 were given

**Comment by vinyll** [comment]
@luk156 A major update was done for Django 4.2. Can you upgrade to Django Imagefit 0.8.0 and see if your error persists?

**Comment by luk156** [comment]
the error is resolved, thks!

**Comment by luk156** [comment]
> dont' work (i'm on django 4.2)
> 
> Traceback (most recent call last): File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner response = get_response(request) File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/Users/matteolucchesi/PycharmProjects/asa-backend/venv/lib/python3.9/site-packages/imagefit/views.py", line 49, in resize sig = Signature(was_modified_since) File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/inspect.py", line 2812, in **init** for param in parameters: TypeError: 'function' object is not iterable

@vinyll

**Comment by Nebuchadrezzar** [comment]
This appears to be the same issue as #48.

**Comment by Nebuchadrezzar** [comment]
@luk156 can we close this issue out?
